version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rtl2cfg-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - ./backend:/app/backend # Optional: live code updates
      - ./cpp_tools:/app/cpp_tools # Optional: access to C++ tools
    environment:
      DJANGO_SETTINGS_MODULE: rtl2cfg.settings
